server:
  port: 8084

jwt:
  secret: xJ5yS1PbV9gQjM/zquVr6zJrLnx6aUOVDOiFSjwwjXU=
  expiration: 186400000

spring:
  devtools:
    livereload:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/powerup_traceability

appDescription: "Microservice Traceability"
appVersion: "1.0.0"
